# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: postgres
  timeout: 5000
  reaping_frequency: 30

# For details on connection pooling, see rails configuration guide
# http://guides.rubyonrails.org/configuring.html#database-pooling

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubydb_development
  password: <%= Rails.application.credentials[:connectionString][:password] %>

test:
  <<: *default
  database: rubydb_test
  password: <%= Rails.application.credentials[:connectionString][:password] %>

production:
  <<: *default
  database: rubydb_production
  password: <%= ENV['EXERCISE_DATABASE_PASSWORD'] %>

